### PR TITLE
Fix #182 and #236

### LINKED ISSUE #182: constraint-sets don't encompass tests, benchmarks, or Haddocks
Currently, if you specify one or more `constraint-set`s (using `haskell-ci`'s `--config`) flag, then it will generate a line in `.travis.yml` for each `constraint-set` that looks like this:

```
  # Constraint set no-mtl
- if [ $HCNUMVER -ge 0 ]; then cabal new-build -w ${HC} --disable-tests --disable-benchmarks --constraint='transformers-compat -mtl' all; else echo skipping...; fi
```

But this only builds the library itself. It doesn't build the tests or benchmarks, and moreover, it doesn't run the tests or build Haddocks, which means that it's possible for things to fail under this `constraint-set` but not be detected by Travis.

This is currently why I don't use `constraint-set`s on more projects, as I can't be sure that I don't accidentally introduce some regression in a non-standard flag configuration.

### PR DESCRIPTION
**Pull request by phadej**
- Add global --run-tests/--no-run-tests/--run-tests-jobs to specify
  when we actually run tests (maybe less then what we build!)

- Add steps configuration to constraint sets:
  - tests
  - run-tests
  - benchmarks
  - haddock
  - these are only booleans for now, if you need more control, make
    another constraint set!

---

cc @RyanGlScott

### CODE REVIEW

File: src/HaskellCI.hs [hunk 1]
```diff
@@ -761,18 +743,24 @@ genTravisFromConfigs argv opts isCabalProject config prj@Project { prjPackages =
...
+            let shForCs = shForJob versions' (csGhcVersions cs)
+            let constraintFlags = concatMap (\x ->  " --constraint='" ++ x ++ "'") (csConstraints cs)
+
             foldedTellStrLns' FoldConstraintSets name ("Constraint set " ++ name) folds $ tellStrLns
-                [ shForJob versions' (csGhcVersions cs) $
-                  cmd ++ " " ++ constraintFlags ++ " all"
-                , ""
+                [ shForCs $ "CSTEST=" ++ if csTests cs then "--enable-tests" else "--disable-tests"
+                , shForCs $ "CSBENCH=" ++ if csBenchmarks cs then "--enable-benchmarks" else "--disable-benchmarks"
+                , shForCs $ "${CABAL} v2-build -w ${HC} ${CSTEST} ${CSBENCH} all " ++ constraintFlags
```
Comment (RyanGlScott) [inline src/HaskellCI.hs]: This is a really minor thing, but is there any reason to use `v2-` here over `new-`, like the rest of `haskell-ci` uses?

File: cabal.haskell-ci [hunk 2]
```diff
@@ -61,6 +61,11 @@ constraint-set deepseq-1.4
   ghc: (>= 7.8 && <7.10) || == 8.2.2
   constraints: deepseq ==1.4.*
 
+  -- tests: False
+  -- run-tests: False
+  -- benchmarks: False
+  haddock: True
```
Comment (RyanGlScott) [inline cabal.haskell-ci]: It would be nice to document `run-tests` here.

File: src/HaskellCI.hs [hunk 3]
```diff
@@ -761,18 +743,24 @@ genTravisFromConfigs argv opts isCabalProject config prj@Project { prjPackages =
...
+
+            let shForCs = shForJob versions' (csGhcVersions cs)
+            let constraintFlags = concatMap (\x ->  " --constraint='" ++ x ++ "'") (csConstraints cs)
+
             foldedTellStrLns' FoldConstraintSets name ("Constraint set " ++ name) folds $ tellStrLns
-                [ shForJob versions' (csGhcVersions cs) $
-                  cmd ++ " " ++ constraintFlags ++ " all"
-                , ""
+                [ shForCs $ "CSTEST=" ++ if csTests cs then "--enable-tests" else "--disable-tests"
+                , shForCs $ "CSBENCH=" ++ if csBenchmarks cs then "--enable-benchmarks" else "--disable-benchmarks"
```
Comment (RyanGlScott) [inline src/HaskellCI.hs]: Since you factor our `CSTEST` and `CSBENCH`, would it make sense to also factor out `constraintFlags` into its own environment variable?

File: src/HaskellCI.hs (hunk 1 above)
Comment (phadej) [reply src/HaskellCI.hs]: I'll slowly convert everything to `v2-` at some point.

File: src/HaskellCI.hs (hunk 3 above)
Comment (phadej) [reply src/HaskellCI.hs]: I did the opposite :)

File: src/HaskellCI.hs [hunk 4]
```diff
@@ -761,18 +743,25 @@ genTravisFromConfigs argv opts isCabalProject config prj@Project { prjPackages =
...
             ]
         forM_ constraintSets $ \cs -> do
             let name = csName cs
-            let constraintFlags = concatMap (\x ->  " --constraint='" ++ x ++ "'") (csConstraints cs)
-            let cmd | csRunTests cs = "${CABAL} new-test  -w ${HC} --enable-tests  --enable-benchmarks"
-                    | otherwise     = "${CABAL} new-build -w ${HC} --disable-tests --disable-benchmarks"
             tellStrLns [ comment $ "Constraint set " ++ name ]
+
+            let shForCs = shForJob versions' (csGhcVersions cs)
+            let testFlag = if csTests cs then " --enable-tests" else " --disable-tests"
```
Comment (RyanGlScott) [inline src/HaskellCI.hs]: The space character in `" --enable-tests"` is unnecessary, since this ends up being fed into `unwords`, which adds the necessary spacing anyways. (Similarly for `" --disable-tests"`, `" --enable-benchmarks"`, and `" --disable-benchmarks"`.)

Comment (phadej) [reply src/HaskellCI.hs]: good catch.

Comment (phadej) [reply src/HaskellCI.hs]: it's interesting that per package `tests: False` overrides cli argument `--enable-tests` btw. I find that slightly weird.

**Comment by phadej** [comment]
I also pushed (hopefully) a fix for #246, if you, @RyanGlScott, mind to check as you are testing this branch

File: src/HaskellCI.hs [hunk 5]
```diff
@@ -1010,7 +1010,7 @@ hlintJobVersionRange vs HLintJobLatest = case S.maxView vs of
 hlintJobVersionRange _ (HLintJob v)   = thisVersion v
 
 hlintArgs :: GenericPackageDescription -> [[String]]
-hlintArgs gpd =
+hlintArgs gpd = nub $
```
Comment (phadej) [inline src/HaskellCI.hs]: note, because extensions could be different let us not `concat` those.

**Comment by RyanGlScott** [comment]
I just tried it out on `lens` and `rcu`, and it appears to do the right thing.
